EXPERIMENT:
  NAME: ""
  TAG: "kd,res32x4,res8,4096_9"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "KD"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8"
SOLVER:
  BATCH_SIZE: 4096
  EPOCHS: 240
  LR: 0.4
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
